### ISSUE TITLE
GraphQLError: Unexpected Name

### ISSUE THREAD

**Issue by alexfornuto** [danspratling/gatsby-source-multi-api#5] opened 2020-02-14 15:39 UTC
Thanks for this plugin! I'm hoping to use it to pull the root response form the WordPress API, to build better documentation around it's functions. The problem is that Gatsby won't build.

## Steps to reproduce:

1. Install the plugin:

    ```
    npm install --save gatsby-source-rest-api
    ```

1.  Configure the plugin, providing a known working endpoint:

    ```
    plugins: [
        {
          resolve: `gatsby-source-rest-api`,
          options: {
            endpoints: [
              `https://scalewp.io/wp-json/wp/v2/`,
             ],
          },
        },

    ...
    ```

1. Resulting error after `gatsby clean && gatsby build`:

    ```
    UNHANDLED REJECTION Syntax Error: Unexpected Name "RestApiWp"



    GraphQLError: Syntax Error: Unexpected Name "RestApiWp"
    
    - TypeMapper.js:113 TypeMapper.createType
        [gatsby]/[graphql-compose]/lib/TypeMapper.js:113:43
    
    - ObjectTypeComposer.js:80 Function.createTemp
        [gatsby]/[graphql-compose]/lib/ObjectTypeComposer.js:80:28
    
    - ObjectTypeComposer.js:56 Function.create
        [gatsby]/[graphql-compose]/lib/ObjectTypeComposer.js:56:21
    
    - index.js:59 typeNames.forEach.typeName
        [gatsby]/[gatsby]/dist/schema/infer/index.js:59:41
    
    - Array.forEach
    
    - index.js:42 addInferredTypes
        [gatsby]/[gatsby]/dist/schema/infer/index.js:42:13
    
    - schema.js:184 updateSchemaComposer
        [gatsby]/[gatsby]/dist/schema/schema.js:184:9
    ````

## Additional Details

It may also be worth noting that the first time I tried to run it, I got:

```
ERROR #11321  PLUGIN

"gatsby-source-rest-api" threw an error while running the sourceNodes lifecycle:

request to https://scalewp.io/wp-json/wp/v2/ failed, reason: Client network socket disconnected before secure TLS connection was established



  FetchError: request to https://scalewp.io/wp-json/wp/v2/ failed, reason: Client network socket disc  onnected before secure TLS connection was established
```

I wonder if an `await` in the fetch of the endpoint could help? IANAD, just a thought. I tried adding it in, but that caused more issues than it solved (as most of my "fixes" tend to do :smile:  )

**Comment by danspratling** [comment] 2020-02-14 16:37
Umm i think getting the root response from wordpress might be a little too big a task for this very unfinished plugin 😅

The plugin is designed to take specific endpoints and break them down into something graphql can understand. So this would usually take something like "/posts" and give it back in graphql format.

Now i'm not entirely sure why this is failing for the wordpress default reponse (it's still json after all).

I'll try and take a look into it over the next week when i have some time and see if i can figure out the issues. I'm happy for you to fork the project if you think you can get somewhere with it too (as it's mostly been left untouched after the initial prototype phase).

**Comment by alexfornuto** [comment] 2020-02-14 17:55
I'm a little out of my depths re: forking. But I appreciate the quick response, and understand the limitations of alpha-level projects. I've defaulted back to providing the data to the project as a json file, provided before build via CI script, but I look forward to re-reviewing this project for other, smaller endpoints I consume.

**Comment by danspratling** [comment] 2020-02-15 19:23
Turns out, this was a lot simpler than I thought. The issue was being caused by the hyphen in the url (wp-json) which was causing a bug when the node was being named (graphql titles can't contain titles). I've now removed hyphens from the url which should fix the bug.

@alexfornuto, could you upgrade your version to 0.2.3 and try it again and let me know how you get on?

Closing this bug as i believe the issue to be fixed but let me know if there's still an issue.

**Closed as completed by danspratling** 2020-02-15 19:23 UTC
Labels: bug

**Comment by alexfornuto** [comment] 2020-02-18 14:14
@danspratling I can confirmed that you resolved this issue, thanks! Prepare for more issues now that I can continue development using this plugin :smile:.
